# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        # Include all pipeline modules
        ('pipeline/', 'pipeline/'),
        # Include web templates and static files
        ('web/templates/', 'web/templates/'),
        ('web/static/', 'web/static/'),
        # Include requirements.txt for reference
        ('requirements.txt', '.'),
        # Include model directory
        ('model/', 'model/'),
        # Include ablations directory
        ('ablations/', 'ablations/'),
    ],
    hiddenimports=[
        # Audio processing
        'librosa',
        'librosa.core',
        'librosa.feature',
        'librosa.effects',
        'librosa.util',
        'librosa.display',
        'soundfile',
        # Scientific computing
        'numpy',
        'numpy.random',
        'scipy',
        'scipy.io',
        'scipy.signal',
        'scipy.fftpack',
        # MIDI processing
        'mido',
        'mido.backends',
        'pretty_midi',
        # Machine learning
        'torch',
        'torch.nn',
        'torch.optim',
        'torch.utils',
        # Data processing
        'pandas',
        'pandas.core',
        'pandas.io',
        # Web framework
        'flask',
        'flask.json',
        'flask_cors',
        'flask.helpers',
        'flask.templating',
        'flask.wrappers',
        'flask.globals',
        'flask.sessions',
        'flask.blueprints',
        'flask.app',
        'flask.config',
        'flask.ctx',
        'flask.testing',
        'flask.logging',
        'flask.cli',
        'flask.signals',
        'flask.debughelpers',
        # ASGI server
        'uvicorn',
        'uvicorn.config',
        'uvicorn.server',
        'uvicorn.loops',
        'uvicorn.protocols',
        'uvicorn.middleware',
        'uvicorn.logging',
        'uvicorn.protocols.http',
        'uvicorn.protocols.websockets',
        # Evaluation metrics
        'mir_eval',
        'mir_eval.util',
        'mir_eval.separation',
        'mir_eval.transcription',
        'mir_eval.onset',
        'mir_eval.chord',
        'mir_eval.segment',
        'mir_eval.util',
        # Progress bars
        'tqdm',
        'tqdm.std',
        'tqdm.utils',
        'tqdm.contrib',
        'tqdm.contrib.concurrent',
        'tqdm.contrib.itertools',
        'tqdm.contrib.logging',
        'tqdm.contrib.discord',
        'tqdm.contrib.telegram',
        'tqdm.contrib.bells',
        'tqdm.contrib.smashtest',
        'tqdm.contrib.multiprocessing',
        # Image processing
        'PIL',
        'PIL.Image',
        'PIL.ImageDraw',
        'PIL.ImageFont',
        'PIL.ImageOps',
        'PIL.ImageFile',
        'PIL.ImageFilter',
        'PIL.ImageMath',
        'PIL.ImageMode',
        'PIL.ImageMorph',
        'PIL.ImagePalette',
        'PIL.ImagePath',
        'PIL.ImageQt',
        'PIL.ImageSequence',
        'PIL.ImageShow',
        'PIL.ImageStat',
        'PIL.ImageTk',
        'PIL.ImageTransform',
        'PIL.ImageWin',
        'PIL.JpegPresets',
        'PIL.TiffImagePlugin',
        'PIL.TiffTags',
        'PIL._tkinter_finder',
        'PIL._util',
        'PIL._version',
        'PIL._webp',
        'PIL.features',
        'PIL.ImageChops',
        'PIL.ImageColor',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Exclude heavy dependencies that are not essential
        'matplotlib',
        'scipy.spatial',
        'scipy.linalg',
        'scipy.special',
        'scipy.sparse',
        'scipy.stats',
        'scipy.io.matlab',
        'pandas.plotting',
        'pandas.io.formats.style',
        'pandas.io.clipboard',
        'pandas.io.formats',
        'pandas.core',
        'pandas.io',
        'numba',
        'llvmlite',
        'tensorflow',
        'torchvision',
        'torchaudio',
        'urllib3',
        'certifi',
        'charset_normalizer',
        'fsspec',
        'zoneinfo',
        'dateutil',
        'jinja2',
        'matplotlib',
        'PIL',
        'PIL.ImageFilter',
        'PIL.ImageMath',
        'PIL.ImageMode',
        'PIL.ImageMorph',
        'PIL.ImagePalette',
        'PIL.ImagePath',
        'PIL.ImageQt',
        'PIL.ImageSequence',
        'PIL.ImageShow',
        'PIL.ImageStat',
        'PIL.ImageTk',
        'PIL.ImageTransform',
        'PIL.ImageWin',
        'PIL.JpegPresets',
        'PIL.TiffImagePlugin',
        'PIL.TiffTags',
        'PIL._tkinter_finder',
        'PIL._util',
        'PIL._version',
        'PIL._webp',
        'PIL.features',
        'PIL.ImageChops',
        'PIL.ImageColor',
    ],
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='blahblah',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='icon.ico'
)